name: flutter_application_9
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4

  # Localization
  flutter_localizations:
    sdk: flutter

  # PDF/Print/Share/Formatting
  pdf: ^3.11.0
  printing: ^5.13.0
  share_plus: ^10.0.2
  intl: ^0.20.2   # <- updated to match flutter_localizations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true