// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhOnSJgmCw6BVFjHr4w3jsxwjxV9XxKR8',
    appId: '1:486399585539:web:313eaee9858ab2804a8d36',
    messagingSenderId: '486399585539',
    projectId: 'pos-720cf',
    authDomain: 'pos-720cf.firebaseapp.com',
    storageBucket: 'pos-720cf.firebasestorage.app',
    measurementId: 'G-HRDTZVC12E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpZD0KqlyliFbTILBmOn2smI1_k3U8jFs',
    appId: '1:486399585539:android:41d961a9f933b13a4a8d36',
    messagingSenderId: '486399585539',
    projectId: 'pos-720cf',
    storageBucket: 'pos-720cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4HzLOjWA_5CBak7myHpaH1lIJfHP7Ghc',
    appId: '1:486399585539:ios:a1c39b5e6329c99d4a8d36',
    messagingSenderId: '486399585539',
    projectId: 'pos-720cf',
    storageBucket: 'pos-720cf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4HzLOjWA_5CBak7myHpaH1lIJfHP7Ghc',
    appId: '1:486399585539:ios:a1c39b5e6329c99d4a8d36',
    messagingSenderId: '486399585539',
    projectId: 'pos-720cf',
    storageBucket: 'pos-720cf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhOnSJgmCw6BVFjHr4w3jsxwjxV9XxKR8',
    appId: '1:486399585539:web:0ed722f621bf0b5a4a8d36',
    messagingSenderId: '486399585539',
    projectId: 'pos-720cf',
    authDomain: 'pos-720cf.firebaseapp.com',
    storageBucket: 'pos-720cf.firebasestorage.app',
    measurementId: 'G-EDXEQY8CMT',
  );

}